Dtd2310900027/Dtd2310900027/Models/DoTungDuong_2310900027Context.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Dtd2310900027.Models;

public partial class DoTungDuong_2310900027Context : DbContext
{
    public DoTungDuong_2310900027Context()
    {
    }

    public DoTungDuong_2310900027Context(DbContextOptions<DoTungDuong_2310900027Context> options)
        : base(options)
    {
    }

    public virtual DbSet<DtdEmployee> DtdEmployees { get; set; }

//    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
//        => optionsBuilder.UseSqlServer("Server=LAPTOPDUONG;Database=DoTungDuong_2310900027;Trusted_Connection=True;MultipleActiveResultSets=True;TrustServerCertificate=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DtdEmployee>(entity =>
        {
            entity.HasKey(e => e.DtdEmpId).HasName("PK__DtdEmplo__A79086D43E31812B");

            entity.ToTable("DtdEmployee");

            entity.Property(e => e.DtdEmpId)
                .ValueGeneratedNever()
                .HasColumnName("dtdEmpId");
            entity.Property(e => e.DtdEmpLevel)
                .HasMaxLength(50)
                .HasColumnName("dtdEmpLevel");
            entity.Property(e => e.DtdEmpName)
                .HasMaxLength(100)
                .HasColumnName("dtdEmpName");
            entity.Property(e => e.DtdEmpStartDate).HasColumnName("dtdEmpStartDate");
            entity.Property(e => e.DtdEmpStatus).HasColumnName("dtdEmpStatus");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

Dtd2310900027/Dtd2310900027/Models/DtdEmployee.cs
using System;
using System.Collections.Generic;

namespace Dtd2310900027.Models;

public partial class DtdEmployee
{
    public int DtdEmpId { get; set; }

    public string? DtdEmpName { get; set; }

    public string? DtdEmpLevel { get; set; }

    public DateOnly? DtdEmpStartDate { get; set; }

    public bool? DtdEmpStatus { get; set; }
}

Dtd2310900027/Dtd2310900027/Models/ErrorViewModel.cs
namespace Dtd2310900027.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Dtd2310900027/Dtd2310900027/Controllers/DtdEmployeesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Dtd2310900027.Models;

namespace Dtd2310900027.Controllers
{
    public class DtdEmployeesController : Controller
    {
        private readonly DoTungDuong_2310900027Context _context;

        public DtdEmployeesController(DoTungDuong_2310900027Context context)
        {
            _context = context;
        }

        // GET: DtdEmployees
        public async Task<IActionResult> DtdIndex()
        {
            return View(await _context.DtdEmployees.ToListAsync());
        }

        // GET: DtdEmployees/Details/5
        public async Task<IActionResult> DtdDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dtdEmployee = await _context.DtdEmployees
                .FirstOrDefaultAsync(m => m.DtdEmpId == id);
            if (dtdEmployee == null)
            {
                return NotFound();
            }

            return View(dtdEmployee);
        }

        // GET: DtdEmployees/Create
        public IActionResult DtdCreate()
        {
            return View();
        }

        // POST: DtdEmployees/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DtdCreate([Bind("DtdEmpId,DtdEmpName,DtdEmpLevel,DtdEmpStartDate,DtdEmpStatus")] DtdEmployee dtdEmployee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dtdEmployee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(DtdIndex));
            }
            return View(dtdEmployee);
        }

        // GET: DtdEmployees/Edit/5
        public async Task<IActionResult> DtdEdit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dtdEmployee = await _context.DtdEmployees.FindAsync(id);
            if (dtdEmployee == null)
            {
                return NotFound();
            }
            return View(dtdEmployee);
        }

        // POST: DtdEmployees/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DtdEdit(int id, [Bind("DtdEmpId,DtdEmpName,DtdEmpLevel,DtdEmpStartDate,DtdEmpStatus")] DtdEmployee dtdEmployee)
        {
            if (id != dtdEmployee.DtdEmpId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dtdEmployee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DtdEmployeeExists(dtdEmployee.DtdEmpId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(DtdIndex));
            }
            return View(dtdEmployee);
        }

        // GET: DtdEmployees/Delete/5
        public async Task<IActionResult> DtdDelete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dtdEmployee = await _context.DtdEmployees
                .FirstOrDefaultAsync(m => m.DtdEmpId == id);
            if (dtdEmployee == null)
            {
                return NotFound();
            }

            return View(dtdEmployee);
        }

        // POST: DtdEmployees/DeleteConfirmed
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DtdDeleteConfirmed(int id)
        {
            var dtdEmployee = await _context.DtdEmployees.FindAsync(id);
            if (dtdEmployee != null)
            {
                _context.DtdEmployees.Remove(dtdEmployee);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(DtdIndex));
        }

        private bool DtdEmployeeExists(int id)
        {
            return _context.DtdEmployees.Any(e => e.DtdEmpId == id);
        }
    }
}

Dtd2310900027/Dtd2310900027/Controllers/DtdHomeController.cs
using System.Diagnostics;
using Dtd2310900027.Models;
using Microsoft.AspNetCore.Mvc;

namespace Dtd2310900027.Controllers
{
    public class DtdHomeController : Controller
    {
        private readonly ILogger<DtdHomeController> _logger;

        public DtdHomeController(ILogger<DtdHomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult DtdIndex()
        {
            return View();
        }

        public IActionResult DtdAbout()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Dtd2310900027/Dtd2310900027/Views/DtdHome/DtdAbout.cshtml
@{
    ViewData["Title"] = "Privacy Policy";
}
<h1>@ViewData["Title"]</h1>


<h2>Thông tin cá nhân</h2>
<p>Họ tên: Đỗ Tùng Dương</p>
<p>Mã sinh viên: 2310900027</p>
<p>Ngày sinh: 16/04/2005</p>

Dtd2310900027/Dtd2310900027/Views/DtdHome/DtdIndex.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Dtd2310900027/Dtd2310900027/Views/Shared/_DtdLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dtd2310900027</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Dtd2310900027.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Dtd2310900027</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DtdHome" asp-action="DtdIndex">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DtdHome" asp-action="DtdAbout">Thong tin Sinh vien</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DtdEmployees" asp-action="DtdIndex">Thong tin Nhan vien va sinh vien </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Dtd2310900027 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>