DtdLesson05/DtdLesson05/Models/Class.cs
namespace DtdLesson05.Models
{
    public class Class
    {
    }
}

DtdLesson05/DtdLesson05/Models/DataModels/DtdMembers.cs
namespace DtdLesson05.Models.DataModels
{
    public class DtdMember
    {
        public string DtdMembersId { get; set; }
        public string DtdUserName { get; set; }
        public string DtdPassword { get; set; }
        public string DtdFullName { get;set; }
        public string DtdEmail { get; set; }
    }
}

DtdLesson05/DtdLesson05/Models/ErrorViewModel.cs
namespace DtdLesson05.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DtdLesson05/DtdLesson05/Controllers/DtdHomeController.cs
using System.Diagnostics;
using DtdLesson05.Models;
using DtdLesson05.Models.DataModels;
using Microsoft.AspNetCore.Mvc;

namespace DtdLesson05.Controllers
{
    public class DtdHomeController : Controller
    {
        private readonly ILogger<DtdHomeController> _logger;

        public DtdHomeController(ILogger<DtdHomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult DtdIndex()
        {
            return View();
        }

        public IActionResult DtdAbout()
        {
            DtdMember dtdMember = new DtdMember();
            dtdMember.DtdMembersId = Guid.NewGuid().ToString();
            dtdMember.DtdUserName = "TungDuong";
            dtdMember.DtdPassword = "123456";
            dtdMember.DtdFullName = "Do Tung Duong";
            dtdMember.DtdEmail = "atgdotungduong@gmail.com";
            return View(dtdMember);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DtdLesson05/DtdLesson05/Controllers/DtdMemberController.cs
using DtdLesson05.Models.DataModels;
using Microsoft.AspNetCore.Mvc;

namespace DtdLesson05.Controllers
{
    public class DtdMemberController : Controller
    {
        public static List<DtdMember> dtdListMember = new List<DtdMember>()
        {
              new DtdMember
            {
                DtdMembersId = "2310900027",
                DtdUserName = " Duong",
                DtdPassword = "123456",
                DtdFullName = "Do Tung Duong",
                DtdEmail = "atgdotungduong@gmail.com"
            },
            new DtdMember
            {
                DtdMembersId = "MB002",
                DtdUserName = "jane_smith",
                DtdPassword = "pass456",
                DtdFullName = "Jane Smith",
                DtdEmail = "jane.smith@gmail.com"
            },
            new DtdMember
            {
                DtdMembersId = "MB003",
                DtdUserName = "alice_walker",
                DtdPassword = "alice@789",
                DtdFullName = "Alice Walker",
                DtdEmail = "alice.walker@gmail.com"
            },
            new DtdMember
            {
                DtdMembersId = "MB004",
                DtdUserName = "bob_martin",
                DtdPassword = "bobPass",
                DtdFullName = "Bob Martin",
                DtdEmail = "bob.martin@gmail.com"
            },
            new DtdMember
            {
                DtdMembersId = "MB005",
                DtdUserName = "emma_nguyen",
                DtdPassword = "emmaSecure!",
                DtdFullName = "Emma Nguyen",
                DtdEmail = "emma.nguyen@gmail.com"
            }
        };
        public IActionResult DtdIndex()
        {
            return View(dtdListMember);
        }
    }
}

DtdLesson05/DtdLesson05/Views/DtdMember/DtdIndex.cshtml
@model IEnumerable<DtdLesson05.Models.DataModels.DtdMember>

@{
    ViewData["Title"] = "Danh sách thành viên";
}

<h1 class="my-4">Danh sách sinh viên</h1>

<table class="table table-bordered table-hover table-striped">
    <thead class="table-dark">
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Tài khoản</th>
            <th scope="col">Mật khẩu</th>
            <th scope="col">Họ tên</th>
            <th scope="col">Email</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var dtdItem in Model)
        {
            <tr>
                <td>@dtdItem.DtdMembersId</td>
                <td>@dtdItem.DtdUserName</td>
                <td>@dtdItem.DtdPassword</td>
                <td>@dtdItem.DtdFullName</td>
                <td>@dtdItem.DtdEmail</td>
            </tr>
        }
    </tbody>
</table>

DtdLesson05/DtdLesson05/Views/Shared/_DtdLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DtdLesson05</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DtdLesson05.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <header>
        @Html.Partial("_DtdNavBar")
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - DtdLesson05 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DtdLesson05/DtdLesson05/Views/Shared/_DtdNavBar.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DtdLesson05</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="DtdHome" asp-action="DtdIndex">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="DtdHome" asp-action="DtdAbout">Thong tin SV</a>
                </li>
             
                <a class="nav-link text-dark" asp-area="" asp-controller="DtdMember" asp-action="DtdIndex">Danh sach sinh vien</a>
                </li>
            </ul>
        </div>
    </div>
</nav>